version: "3.5"
services:
    nginx:
      build:
        context: ./
        dockerfile: .docker/nginx/nginx.docker
      ports:
        - "8080:80"
      volumes:
        - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./:/var/www
      depends_on:
        - php-fpm
    php-fpm:
        container_name: php-fpm
        build:
            context: ./
            dockerfile: .docker/php/fpm/Dockerfile
        working_dir: /var/www
        restart: always
        volumes:
            - .:/var/www
            - composer:/root/.composer/cache
        depends_on:
          - mysql
    mysql:
      image: mysql:5.7
      volumes:
        - ./storage/docker/mysql:/var/lib/mysql
      environment:
        - "MYSQL_ROOT_PASSWORD=secret"
        - "MYSQL_USER=app"
        - "MYSQL_PASSWORD=secret"
        - "MYSQL_DATABASE=app"
      ports:
        - "33061:3306"
volumes:
    composer:
